goat_account.home:
    path:     /
    defaults: { _controller: 'GoatAccountBundle:Account:self' }

goat_account.login:
    path:     /login
    defaults: { _controller: 'GoatAccountBundle:Security:login' }

goat_account.request_password:
    path:     /login/request-password
    defaults: { _controller: 'GoatAccountBundle:Security:requestPassword' }

goat_account.change_password:
    path:     /change-password
    defaults: { _controller: 'GoatAccountBundle:Security:changePassword' }

goat_account.one_time_login:
    path:     /login/one/{accountId}/{token}
    defaults: { _controller: 'GoatAccountBundle:Security:oneTimeLogin' }

goat_account.login_check:
    path:     /login/go

goat_account.logout:
    path:     /logout

goat_account.profile_view:
    path:     /{id}
    defaults: { _controller: 'GoatAccountBundle:Account:view' }
    requirements:
        id: \d+
